extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  filelog:
    include: [ ./logfile/*.txt ]
    start_at: beginning

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: 'us-west-2'
  awsemf:
    region: 'us-west-2'
  awscloudwatchlogs:
    log_group_name: "TestLogGroup"
    log_stream_name: "TestLogStream"
    region: "us-west-2"
    log_retention: 365

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    #metrics:
    #  receivers: [otlp]
    #  exporters: [awsemf]
    logs:
      receivers: [filelog]
      exporters: [awscloudwatchlogs]

  extensions: [pprof]
  telemetry:
    logs:
      level: debug